Repository seongmik-s-team/miniRT, pull requests merged in 2024-02, with the labels that each got.

#8 Vector
  Makefile
  includes/minirt.h
  srcs/minirt.c
  srcs/object/mr_object.c
  srcs/vector/vec_new.c
  srcs/vector/vec_oper_basic.c
  srcs/vector/vec_oper_linear_a.c
Labels: enhancement

#9 [MERGE] temp commit for merge
  Makefile
  README.md
  includes/minirt.h
  libft/includes/libft.h
  srcs/minirt.c
  srcs/parser/parser.c
Labels: enhancement

#12 [MERGE] 협업 세팅을 위한 중간 merge
  Makefile
  includes/minirt.h
  libft/includes/libft.h
  libft/srcs/ft_split.c
  libft/srcs/ft_strtrim.c
  libft/srcs/get_next_line.c
  libft/srcs/get_next_line_utils.c
  miniRT
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/error/error.c
  srcs/minirt.c
  srcs/object/cylinder.c
  srcs/object/object.c
  srcs/object/plane.c
  srcs/object/sphere.c
  srcs/parser/add_to_scene.c
  srcs/parser/parser.c
  srcs/parser/utils.c
  srcs/parser/utils2.c
Labels: enhancement

#15 [BUGFIX] Makefile bugfix, 뷰포트 bugfix
  Makefile
  a.rt
  srcs/parser/add_to_scene.c
  srcs/ray/ray.c
Labels: bug

#19 [MERGE] 더욱 엄정해진 Parsing Error 처리
  a.rt
  includes/minirt.h
  libft/srcs/ft_atoi.c
  libft/srcs/ft_split.c
  mlx/mlx_image.swiftdoc
  mlx/mlx_image.swiftmodule
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftdoc
  mlx/mlx_init.swiftmodule
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftdoc
  mlx/mlx_window.swiftmodule
  mlx/mlx_window.swiftsourceinfo
  srcs/cylinder/cylinder.c
  srcs/light/light.c
  srcs/parser/add_to_scene.c
  srcs/parser/parser.c
  srcs/parser/utils2.c
  srcs/plane/plane.c
  srcs/sphere/sphere.c
Labels: bug

#20 [FEATURE] 구, 광원, 그림자, 평면 구현
  Makefile
  a.rt
  includes/minirt.h
  srcs/color/color.c
  srcs/hit/hit.c
  srcs/hit/just_hit.c
  srcs/light/light.c
  srcs/light/shadow.c
  srcs/mlx/mr_mlx.c
  srcs/plane/plane.c
  srcs/ray/ray.c
  srcs/scene/scene.c
  srcs/vector/vec_oper_basic.c
Labels: enhancement

#21 [FEATURE] orientation vector를 반영한 카메라 시점 변화기능 추가
  a.rt
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/hit/hit.c
  srcs/parser/add_to_scene.c
  srcs/plane/plane.c
Labels: enhancement

#22 [BUGFIX] 스피어 여러개 겹치는 경우 버그 수정
  a.rt
  srcs/hit/hit.c
Labels: enhancement

#23 [BUGFIX] 기울어진 좌표계 수정
  a.rt
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/parser/add_to_scene.c
  srcs/vector/vec_oper_linear_a.c
Labels: bug

#25 [TEMP] 작업 분기를 위한 임시 머지
  Makefile
  a.rt
  includes/minirt.h
  srcs/cylinder/cylinder.c
  srcs/cylinder/cylinder_cap.c
  srcs/cylinder/cylinder_side.c
  srcs/cylinder/utils.c
  srcs/hit/hit.c
  srcs/hit/just_hit.c
  srcs/light/shadow.c
  srcs/mlx/mr_mlx.c
  srcs/parser/add_to_scene.c
  srcs/parser/utils2.c
  srcs/plane/plane.c
  srcs/ray/ray.c
Labels: test

#26 [BUGFIX] Sphere 내부 조명 등 여러 버그 수정
  a.rt
  includes/minirt.h
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/hit/hit.c
  srcs/hit/just_hit.c
  srcs/light/light.c
  srcs/light/shadow.c
  srcs/parser/add_to_scene.c
  srcs/plane/plane.c
Labels: bug

#27 [MEGE] 원기둥 기본 구현 완료. (밑면끼리 겹치는 문제 있음)
  a.rt
  includes/minirt.h
  srcs/cylinder/cylinder.c
  srcs/cylinder/cylinder_cap.c
Labels: enhancement

#30 [MERGE] 원기둥 외부 구현 완료. 궁극의 사진 첨부
  a.rt
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/cylinder/cylinder.c
  srcs/cylinder/cylinder_cap.c
  srcs/cylinder/cylinder_side.c
  srcs/cylinder/utils.c
Labels: enhancement

#32 [BUGFIX] plane 원점을 지나지 않을 때 충돌판정 버그 수정
  a.rt
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/hit/just_hit.c
  srcs/plane/plane.c
Labels: bug

#33 [FEATURE] 카메라 이동, 카메라 회전, 랜더링 기능 추가
  Makefile
  includes/minirt.h
  miniRT
  mlx/mlx_image.swiftdoc
  mlx/mlx_image.swiftmodule
  mlx/mlx_init.swiftdoc
  mlx/mlx_init.swiftmodule
  mlx/mlx_window.swiftdoc
  mlx/mlx_window.swiftmodule
  srcs/mlx/hooks.c
  srcs/mlx/mr_mlx.c
  srcs/parser/add_to_scene.c
Labels: enhancement

#34 [FEATURE] 완전한 원기둥 구현 완료
  includes/minirt.h
  srcs/cylinder/cylinder_cap.c
  srcs/cylinder/cylinder_side.c
  srcs/error/error.c
  srcs/light/light.c
  srcs/parser/add_to_scene.c
  srcs/parser/parser.c
Labels: enhancement

#35 [FEATURE] 키연속 입력 기능, 라이트 위치 설정 기능 추가
  includes/minirt.h
  miniRT
  mlx/mlx_image.swiftdoc
  mlx/mlx_image.swiftmodule
  mlx/mlx_init.swiftdoc
  mlx/mlx_init.swiftmodule
  mlx/mlx_window.swiftdoc
  mlx/mlx_window.swiftmodule
  srcs/light/light.c
  srcs/mlx/hooks.c
  srcs/mlx/mr_mlx.c
Labels: enhancement

#36 [BUGFIX] 내부 광원 충돌판정 앱실론 적용으로 변경
  a.rt
  includes/minirt.h
  srcs/cylinder/cylinder_cap.c
  srcs/cylinder/cylinder_side.c
  srcs/hit/hit.c
  srcs/hit/just_hit.c
  srcs/light/shadow.c
  srcs/plane/plane.c
Labels: bug, enhancement

#37 [FEATURE] 주석제거 및 파일 디렉토리 정리
  Makefile
  a.rt
  includes/minirt.h
  libft/includes/libft.h
  libft/srcs/ft_del_node_and_link.c
  libft/srcs/ft_intlen.c
  libft/srcs/ft_isinteger.c
  libft/srcs/ft_list_append.c
  libft/srcs/ft_list_clear.c
  libft/srcs/ft_list_iter.c
  libft/srcs/ft_list_pop.c
  libft/srcs/ft_listget.c
  libft/srcs/ft_replace_node_with_list.c
  libft/srcs/get_next_line_utils.c
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/ambient/ambient.c
  srcs/camera/camera.c
  srcs/circle/circle.c
  srcs/color/color.c
  srcs/color/color2.c
  srcs/cylinder/cylinder.c
  srcs/cylinder/cylinder_cap.c
  srcs/cylinder/cylinder_side.c
  srcs/cylinder/utils.c
  srcs/hit/hit.c
  srcs/hit/just_hit.c
  srcs/light/light.c
  srcs/light/shadow.c
  srcs/minirt.c
  srcs/mlx/hooks.c
  srcs/mlx/mr_mlx.c
  srcs/mlx/mr_mlx_image.c
  srcs/object/object.c
  srcs/parser/add_to_scene.c
  srcs/parser/parser.c
  srcs/parser/utils.c
  srcs/parser/utils2.c
  srcs/plane/plane.c
  srcs/ray/ray.c
  srcs/scene/scene.c
  srcs/sphere/sphere.c
  srcs/vector/vec_new.c
Labels: enhancement

#40 [NORMINETTE] cylinder norm correct
  a.rt
  mlx/mlx_image.swiftsourceinfo
  mlx/mlx_init.swiftsourceinfo
  mlx/mlx_window.swiftsourceinfo
  srcs/cylinder/cylinder_cap.c
  srcs/cylinder/cylinder_side.c
Labels: enhancement

#39 [FEATURE] 실행환경의 Endian, Pixel per color를 고려한 랜더링 적용
  Makefile
  a.rt
  includes/minirt.h
  srcs/color/color.c
  srcs/color/color_rgb.c
  srcs/minirt.c
  srcs/mlx/hooks.c
  srcs/mlx/mr_mlx.c
  srcs/mlx/mr_mlx_destroy.c
  srcs/mlx/mr_mlx_image.c
  srcs/ray/ray.c
Labels: enhancement

#41 [LAST] Makefile header 추가 및 argc 에러 처리
  libft/Makefile
  srcs/minirt.c
Labels: enhancement

#42 [BUGFIX] perror -> write
  a.rt
  srcs/error/error.c
Labels: enhancement
